"""incoming column added

Revision ID: 21d9614ee9d5
Revises: 9ed7a2908a70
Create Date: 2019-05-04 14:31:19.248286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d9614ee9d5'
down_revision = '9ed7a2908a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incoming', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('incoming')

    # ### end Alembic commands ###
