# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='personal_finance_tool',
    version='0.1.0',
    description='A simple web application to track your personal finances.',
    python_requires='==3.*,>=3.8.0',
    author='JeffreyThijs',
    author_email='jeffrey.thijs@hotmail.com',
    packages=[
        'app.api', 'app.api.api_v1', 'app.api.api_v1.endpoints',
        'app.api.api_v1.endpoints.transactions', 'app.api.common', 'app.crud',
        'app.fastapi_users', 'app.storage.schemas'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'aiofiles', 'alembic', 'asyncpg', 'databases', 'fastapi',
        'fastapi-mail', 'fastapi-users', 'fastapi-utils', 'gunicorn',
        'httptools', 'httpx-oauth', 'pendulum', 'psycopg2', 'pydantic',
        'pydantic-sqlalchemy', 'pytest-asyncio', 'python-dotenv', 'setuptools',
        'sqlalchemy==1.4.0b1', 'starlette', 'uvicorn', 'uvloop'
    ],
    extras_require={
        "dev": [
            "autopep8", "faker", "pytest", "pytest-cov", "pytest-postgresql",
            "requests"
        ]
    },
)
