"""added date transaction

Revision ID: 24015b0d7669
Revises: d365b9b6a097
Create Date: 2020-11-15 10:18:36.193051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24015b0d7669'
down_revision = 'd365b9b6a097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
