"""add transaction table

Revision ID: d365b9b6a097
Revises: 86821a36a853
Create Date: 2020-11-12 23:13:35.669600

"""
from alembic import op
import sqlalchemy as sa
from fastapi_users.db.sqlalchemy import GUID


# revision identifiers, used by Alembic.
revision = 'd365b9b6a097'
down_revision = '86821a36a853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
