"""added tags to transaction

Revision ID: fdcc7a2a72f6
Revises: 24015b0d7669
Create Date: 2020-11-28 15:57:15.249607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdcc7a2a72f6'
down_revision = '24015b0d7669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tags')
    # ### end Alembic commands ###
