"""add type to transaction (autogen)

Revision ID: 8a5708d814e1
Revises: b6ff8fbdad69
Create Date: 2019-04-28 18:21:29.361813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5708d814e1'
down_revision = 'b6ff8fbdad69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'type')
    # ### end Alembic commands ###
