"""Add prognosis model

Revision ID: 9c56f540f58f
Revises: 2675af6ce1bd
Create Date: 2019-11-16 16:14:41.756237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import logging

# revision identifiers, used by Alembic.
revision = '9c56f540f58f'
down_revision = '2675af6ce1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prognosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('incoming', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('DAILY', 'MONTHLY', 'YEARLY', 'ONCE', name='prognosisoccurancetype'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prognosis'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prognosis')
    # ### end Alembic commands ###

    # delete enum type as current alembic setup does not generate it?
    try:
        prognosis_occurance_type = postgresql.ENUM('DAILY', 'MONTHLY', 'YEARLY', 'ONCE', name='prognosisoccurancetype')
        prognosis_occurance_type.drop(op.get_bind())
    except:
        logging.error("Cant remove prognosis_occurance_type")
    